# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20160127_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_id',
            new_name='sensor_id_const',
        ),
    ]
